openapi: 3.0.0
info:
  title: Vacancy Create Service
  version: 1.0.0
  description: RESTful API to register new job vacancies on the UNIBRIDGE platform.
paths:
  /api/vacancies:
    post:
      summary: Create a new vacancy
      description: This endpoint allows companies to register a new job vacancy in the UNIBRIDGE system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - titulo
                - descripcion
                - empresa_id
                - ciudad
                - carrera
                - estado
                - fecha_publicacion
              properties:
                titulo:
                  type: string
                  description: Job title.
                descripcion:
                  type: string
                  description: Detailed description of responsibilities and requirements.
                empresa_id:
                  type: integer
                  description: Numeric ID of the company posting the vacancy.
                ciudad:
                  type: string
                  description: City where the job is offered.
                carrera:
                  type: string
                  description: University career or field related to the vacancy.
                estado:
                  type: string
                  description: Current status of the vacancy (e.g., active, closed).
                fecha_publicacion:
                  type: string
                  format: date
                  description: Publication date of the vacancy (format YYYY-MM-DD).
      responses:
        '201':
          description: Vacancy created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Vacancy created successfully
        '400':
          description: Missing required fields or invalid data
        '500':
          description: Internal server or database error