// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protos/practice.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for a single practice
type Practice struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VacanteId          int32                  `protobuf:"varint,2,opt,name=vacante_id,json=vacanteId,proto3" json:"vacante_id,omitempty"`
	FechaInicio        string                 `protobuf:"bytes,3,opt,name=fecha_inicio,json=fechaInicio,proto3" json:"fecha_inicio,omitempty"`
	FechaFin           string                 `protobuf:"bytes,4,opt,name=fecha_fin,json=fechaFin,proto3" json:"fecha_fin,omitempty"`
	TutorAcademicoId   string                 `protobuf:"bytes,5,opt,name=tutor_academico_id,json=tutorAcademicoId,proto3" json:"tutor_academico_id,omitempty"`
	TutorEmpresarialId string                 `protobuf:"bytes,6,opt,name=tutor_empresarial_id,json=tutorEmpresarialId,proto3" json:"tutor_empresarial_id,omitempty"`
	Estado             string                 `protobuf:"bytes,7,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Practice) Reset() {
	*x = Practice{}
	mi := &file_protos_practice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Practice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Practice) ProtoMessage() {}

func (x *Practice) ProtoReflect() protoreflect.Message {
	mi := &file_protos_practice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Practice.ProtoReflect.Descriptor instead.
func (*Practice) Descriptor() ([]byte, []int) {
	return file_protos_practice_proto_rawDescGZIP(), []int{0}
}

func (x *Practice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Practice) GetVacanteId() int32 {
	if x != nil {
		return x.VacanteId
	}
	return 0
}

func (x *Practice) GetFechaInicio() string {
	if x != nil {
		return x.FechaInicio
	}
	return ""
}

func (x *Practice) GetFechaFin() string {
	if x != nil {
		return x.FechaFin
	}
	return ""
}

func (x *Practice) GetTutorAcademicoId() string {
	if x != nil {
		return x.TutorAcademicoId
	}
	return ""
}

func (x *Practice) GetTutorEmpresarialId() string {
	if x != nil {
		return x.TutorEmpresarialId
	}
	return ""
}

func (x *Practice) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

// Response containing a list of practices
type GetPracticesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Practices     []*Practice            `protobuf:"bytes,1,rep,name=practices,proto3" json:"practices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPracticesResponse) Reset() {
	*x = GetPracticesResponse{}
	mi := &file_protos_practice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPracticesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPracticesResponse) ProtoMessage() {}

func (x *GetPracticesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_practice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPracticesResponse.ProtoReflect.Descriptor instead.
func (*GetPracticesResponse) Descriptor() ([]byte, []int) {
	return file_protos_practice_proto_rawDescGZIP(), []int{1}
}

func (x *GetPracticesResponse) GetPractices() []*Practice {
	if x != nil {
		return x.Practices
	}
	return nil
}

var File_protos_practice_proto protoreflect.FileDescriptor

const file_protos_practice_proto_rawDesc = "" +
	"\n" +
	"\x15protos/practice.proto\x12\bpractice\"\xf1\x01\n" +
	"\bPractice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"vacante_id\x18\x02 \x01(\x05R\tvacanteId\x12!\n" +
	"\ffecha_inicio\x18\x03 \x01(\tR\vfechaInicio\x12\x1b\n" +
	"\tfecha_fin\x18\x04 \x01(\tR\bfechaFin\x12,\n" +
	"\x12tutor_academico_id\x18\x05 \x01(\tR\x10tutorAcademicoId\x120\n" +
	"\x14tutor_empresarial_id\x18\x06 \x01(\tR\x12tutorEmpresarialId\x12\x16\n" +
	"\x06estado\x18\a \x01(\tR\x06estado\"H\n" +
	"\x14GetPracticesResponse\x120\n" +
	"\tpractices\x18\x01 \x03(\v2\x12.practice.PracticeR\tpracticesB]Z[github.com/Niikyes/UNIBRIDGE/backend/domains/student_management/practice-get-service/protosb\x06proto3"

var (
	file_protos_practice_proto_rawDescOnce sync.Once
	file_protos_practice_proto_rawDescData []byte
)

func file_protos_practice_proto_rawDescGZIP() []byte {
	file_protos_practice_proto_rawDescOnce.Do(func() {
		file_protos_practice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_practice_proto_rawDesc), len(file_protos_practice_proto_rawDesc)))
	})
	return file_protos_practice_proto_rawDescData
}

var file_protos_practice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_practice_proto_goTypes = []any{
	(*Practice)(nil),             // 0: practice.Practice
	(*GetPracticesResponse)(nil), // 1: practice.GetPracticesResponse
}
var file_protos_practice_proto_depIdxs = []int32{
	0, // 0: practice.GetPracticesResponse.practices:type_name -> practice.Practice
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_practice_proto_init() }
func file_protos_practice_proto_init() {
	if File_protos_practice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_practice_proto_rawDesc), len(file_protos_practice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_practice_proto_goTypes,
		DependencyIndexes: file_protos_practice_proto_depIdxs,
		MessageInfos:      file_protos_practice_proto_msgTypes,
	}.Build()
	File_protos_practice_proto = out.File
	file_protos_practice_proto_goTypes = nil
	file_protos_practice_proto_depIdxs = nil
}
