openapi: 3.0.0
info:
  title: Practice Create Service API
  version: "1.0"
  description: API to create a new professional practice for students.
servers:
  - url: http://localhost:5000
paths:
  /api/practice/create:
    post:
      summary: Create a new practice
      description: Creates a new professional practice for a student after being accepted by a company.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - estudiante_id
                - vacante_id
                - fecha_inicio
                - fecha_fin
                - tutor_academico_id
                - tutor_empresarial_id
              properties:
                estudiante_id:
                  type: string
                  format: uuid
                  example: "28b565be-55b0-4f47-a8b7-1acbdef41234"
                vacante_id:
                  type: integer
                  example: 12
                fecha_inicio:
                  type: string
                  format: date
                  example: "2025-07-01"
                fecha_fin:
                  type: string
                  format: date
                  example: "2025-09-30"
                tutor_academico_id:
                  type: string
                  format: uuid
                  example: "c9ac2eb1-6c91-4673-a58b-4cc122f21234"
                tutor_empresarial_id:
                  type: string
                  format: uuid
                  example: "f28cba13-85e1-45d5-9332-bc4e41a61234"
      responses:
        "201":
          description: Practice created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Practice created successfully
                  practice_id:
                    type: integer
                    example: 1
        "400":
          description: Bad request (validation error)
        "500":
          description: Internal server error
