openapi: 3.0.0
info:
  title: vacancy-get-all-service
  version: 1.0.0
  description: >
    Microservice that exposes a GraphQL endpoint to retrieve all internship vacancies from MongoDB.
servers:
  - url: http://localhost:8000
paths:
  /graphql:
    post:
      summary: Execute GraphQL query to fetch all vacancies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "{ allVacancies { id title description start_date careers company_id } }"
      responses:
        '200':
          description: GraphQL query executed successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
