// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protos/practice.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structure to create a new practice
type CreatePracticeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EstudianteId       string                 `protobuf:"bytes,1,opt,name=estudiante_id,json=estudianteId,proto3" json:"estudiante_id,omitempty"`
	VacanteId          int32                  `protobuf:"varint,2,opt,name=vacante_id,json=vacanteId,proto3" json:"vacante_id,omitempty"`
	FechaInicio        string                 `protobuf:"bytes,3,opt,name=fecha_inicio,json=fechaInicio,proto3" json:"fecha_inicio,omitempty"`
	FechaFin           string                 `protobuf:"bytes,4,opt,name=fecha_fin,json=fechaFin,proto3" json:"fecha_fin,omitempty"`
	TutorAcademicoId   string                 `protobuf:"bytes,5,opt,name=tutor_academico_id,json=tutorAcademicoId,proto3" json:"tutor_academico_id,omitempty"`
	TutorEmpresarialId string                 `protobuf:"bytes,6,opt,name=tutor_empresarial_id,json=tutorEmpresarialId,proto3" json:"tutor_empresarial_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreatePracticeRequest) Reset() {
	*x = CreatePracticeRequest{}
	mi := &file_protos_practice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePracticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePracticeRequest) ProtoMessage() {}

func (x *CreatePracticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_practice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePracticeRequest.ProtoReflect.Descriptor instead.
func (*CreatePracticeRequest) Descriptor() ([]byte, []int) {
	return file_protos_practice_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePracticeRequest) GetEstudianteId() string {
	if x != nil {
		return x.EstudianteId
	}
	return ""
}

func (x *CreatePracticeRequest) GetVacanteId() int32 {
	if x != nil {
		return x.VacanteId
	}
	return 0
}

func (x *CreatePracticeRequest) GetFechaInicio() string {
	if x != nil {
		return x.FechaInicio
	}
	return ""
}

func (x *CreatePracticeRequest) GetFechaFin() string {
	if x != nil {
		return x.FechaFin
	}
	return ""
}

func (x *CreatePracticeRequest) GetTutorAcademicoId() string {
	if x != nil {
		return x.TutorAcademicoId
	}
	return ""
}

func (x *CreatePracticeRequest) GetTutorEmpresarialId() string {
	if x != nil {
		return x.TutorEmpresarialId
	}
	return ""
}

type CreatePracticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PracticaId    int32                  `protobuf:"varint,2,opt,name=practica_id,json=practicaId,proto3" json:"practica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePracticeResponse) Reset() {
	*x = CreatePracticeResponse{}
	mi := &file_protos_practice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePracticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePracticeResponse) ProtoMessage() {}

func (x *CreatePracticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_practice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePracticeResponse.ProtoReflect.Descriptor instead.
func (*CreatePracticeResponse) Descriptor() ([]byte, []int) {
	return file_protos_practice_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePracticeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePracticeResponse) GetPracticaId() int32 {
	if x != nil {
		return x.PracticaId
	}
	return 0
}

var File_protos_practice_proto protoreflect.FileDescriptor

const file_protos_practice_proto_rawDesc = "" +
	"\n" +
	"\x15protos/practice.proto\x12\bpractice\"\xfb\x01\n" +
	"\x15CreatePracticeRequest\x12#\n" +
	"\restudiante_id\x18\x01 \x01(\tR\festudianteId\x12\x1d\n" +
	"\n" +
	"vacante_id\x18\x02 \x01(\x05R\tvacanteId\x12!\n" +
	"\ffecha_inicio\x18\x03 \x01(\tR\vfechaInicio\x12\x1b\n" +
	"\tfecha_fin\x18\x04 \x01(\tR\bfechaFin\x12,\n" +
	"\x12tutor_academico_id\x18\x05 \x01(\tR\x10tutorAcademicoId\x120\n" +
	"\x14tutor_empresarial_id\x18\x06 \x01(\tR\x12tutorEmpresarialId\"S\n" +
	"\x16CreatePracticeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vpractica_id\x18\x02 \x01(\x05R\n" +
	"practicaIdB`Z^github.com/Niikyes/UNIBRIDGE/backend/domains/student_management/practice-create-service/protosb\x06proto3"

var (
	file_protos_practice_proto_rawDescOnce sync.Once
	file_protos_practice_proto_rawDescData []byte
)

func file_protos_practice_proto_rawDescGZIP() []byte {
	file_protos_practice_proto_rawDescOnce.Do(func() {
		file_protos_practice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_practice_proto_rawDesc), len(file_protos_practice_proto_rawDesc)))
	})
	return file_protos_practice_proto_rawDescData
}

var file_protos_practice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_practice_proto_goTypes = []any{
	(*CreatePracticeRequest)(nil),  // 0: practice.CreatePracticeRequest
	(*CreatePracticeResponse)(nil), // 1: practice.CreatePracticeResponse
}
var file_protos_practice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_practice_proto_init() }
func file_protos_practice_proto_init() {
	if File_protos_practice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_practice_proto_rawDesc), len(file_protos_practice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_practice_proto_goTypes,
		DependencyIndexes: file_protos_practice_proto_depIdxs,
		MessageInfos:      file_protos_practice_proto_msgTypes,
	}.Build()
	File_protos_practice_proto = out.File
	file_protos_practice_proto_goTypes = nil
	file_protos_practice_proto_depIdxs = nil
}
