openapi: 3.0.0
info:
  title: Practice Finalize Service API
  version: "1.0"
  description: API to finalize a professional practice by ID.
servers:
  - url: http://localhost:5003
paths:
  /api/practice/{id}/finalize:
    put:
      summary: Finalize a practice
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Practice ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fecha_fin:
                  type: string
                  format: date
                  example: "2025-09-30"
      responses:
        "200":
          description: Practice finalized successfully
        "400":
          description: Invalid input
        "500":
          description: Internal server error
