openapi: 3.0.0
info:
  title: User Get Profile Service
  version: 1.0.0
  description: Returns user profile based on JWT token (student or company).
paths:
  /api/profile:
    get:
      summary: Get authenticated user profile
      description: Returns detailed user info extracted from JWT.
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: Bearer JWT token
      responses:
        '200':
          description: Profile data
          content:
            application/json:
              example:
                user_id: uuid
                nickname: Nicole
                email: nicole@correo.com
                role: estudiante
                estudiante_id: uuid
                universidad_id: uuid
                carrera_id: uuid
                facultad_id: uuid
        '401':
          description: Invalid or missing token
