name: Deploy Vacancy Domain to EC2

on:
  push:
    branches:
      - unibridge-QA

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user services
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vacancy-create-service ./backend/domains/vacancy/vacancy-create-service
          docker push ${{ secrets.DOCKER_USERNAME }}/vacancy-create-service

          docker build -t ${{ secrets.DOCKER_USERNAME }}/vacancy-get-all-service ./backend/domains/vacancy/vacancy-get-all-service
          docker push ${{ secrets.DOCKER_USERNAME }}/vacancy-get-all-service

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy vacancy services to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_VACANCY_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_VACANCY_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y docker.io docker-compose
            sudo systemctl enable docker
            sudo systemctl start docker

            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            cd /home/ubuntu/vacancy

            sudo docker-compose down
            sudo docker system prune -af
            sudo docker-compose pull
            sudo docker-compose up -d
