// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protos/practice.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to finalize a practice
type FinalizePracticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            // ID of the practice to finalize
	FechaFin      string                 `protobuf:"bytes,2,opt,name=fecha_fin,json=fechaFin,proto3" json:"fecha_fin,omitempty"` // Optional: new end date in YYYY-MM-DD format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePracticeRequest) Reset() {
	*x = FinalizePracticeRequest{}
	mi := &file_protos_practice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePracticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePracticeRequest) ProtoMessage() {}

func (x *FinalizePracticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_practice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePracticeRequest.ProtoReflect.Descriptor instead.
func (*FinalizePracticeRequest) Descriptor() ([]byte, []int) {
	return file_protos_practice_proto_rawDescGZIP(), []int{0}
}

func (x *FinalizePracticeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FinalizePracticeRequest) GetFechaFin() string {
	if x != nil {
		return x.FechaFin
	}
	return ""
}

// Response after finalization
type FinalizePracticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePracticeResponse) Reset() {
	*x = FinalizePracticeResponse{}
	mi := &file_protos_practice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePracticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePracticeResponse) ProtoMessage() {}

func (x *FinalizePracticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_practice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePracticeResponse.ProtoReflect.Descriptor instead.
func (*FinalizePracticeResponse) Descriptor() ([]byte, []int) {
	return file_protos_practice_proto_rawDescGZIP(), []int{1}
}

func (x *FinalizePracticeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_practice_proto protoreflect.FileDescriptor

const file_protos_practice_proto_rawDesc = "" +
	"\n" +
	"\x15protos/practice.proto\x12\bpractice\"F\n" +
	"\x17FinalizePracticeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tfecha_fin\x18\x02 \x01(\tR\bfechaFin\"4\n" +
	"\x18FinalizePracticeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\"Z practice-finalize-service/protosb\x06proto3"

var (
	file_protos_practice_proto_rawDescOnce sync.Once
	file_protos_practice_proto_rawDescData []byte
)

func file_protos_practice_proto_rawDescGZIP() []byte {
	file_protos_practice_proto_rawDescOnce.Do(func() {
		file_protos_practice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_practice_proto_rawDesc), len(file_protos_practice_proto_rawDesc)))
	})
	return file_protos_practice_proto_rawDescData
}

var file_protos_practice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_practice_proto_goTypes = []any{
	(*FinalizePracticeRequest)(nil),  // 0: practice.FinalizePracticeRequest
	(*FinalizePracticeResponse)(nil), // 1: practice.FinalizePracticeResponse
}
var file_protos_practice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_practice_proto_init() }
func file_protos_practice_proto_init() {
	if File_protos_practice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_practice_proto_rawDesc), len(file_protos_practice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_practice_proto_goTypes,
		DependencyIndexes: file_protos_practice_proto_depIdxs,
		MessageInfos:      file_protos_practice_proto_msgTypes,
	}.Build()
	File_protos_practice_proto = out.File
	file_protos_practice_proto_goTypes = nil
	file_protos_practice_proto_depIdxs = nil
}
